export { app, auth, db, storage, firebaseConfig } from "./config";
export { collections, docs } from "./collections";
export {
    setupRecaptcha,
    sendOTP,
    verifyOTP,
    signOut,
    onAuthChange,
} from "./auth";
export {
    createUser,
    getUser,
    updateUser,
    createShop,
    getShop,
    getShopsByZone,
    getShopsByCategory,
    getAllShops,
    createFeedPost,
    getFeedPost,
    getFeedPosts,
    getFeedPostsByCategory,
    getUserFeedPosts,
    updateFeedPost,
    deleteFeedPost,
    toggleInterested,
    createMarketplaceListing,
    getMarketplaceListing,
    getMarketplaceListings,
    createResponse,
    getResponsesForPost,
    trackWhatsAppTap,
    createNotification,
    getNotifications,
    markNotificationRead,
    getUnreadNotificationCount,
    createReport,
    logActivity,
} from "./firestore-service";
export {
    uploadImage,
    deleteImage,
    generateImagePath,
    getR2ImageUrl,
} from "./storage";
